# Generated by Django 3.1.4 on 2020-12-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=300)),
                ('createdDatetime', models.DateTimeField(verbose_name='task created datetime')),
                ('finishedDatetime', models.DateTimeField(verbose_name='task finished datetime')),
                ('taskDone', models.BooleanField(default=False)),
            ],
        ),
    ]
