# Generated by Django 3.1.4 on 2020-12-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_todolist_taskcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='taskContent',
            field=models.TextField(null=True),
        ),
    ]
