# Generated by Django 3.1.4 on 2020-12-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20201230_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='taskContent',
            field=models.TextField(default=''),
        ),
    ]
