# Generated by Django 3.1.4 on 2020-12-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20201231_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='taskContent',
            field=models.CharField(max_length=600),
        ),
    ]
