# Generated by Django 3.1.4 on 2020-12-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20201231_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='taskContent',
            field=models.TextField(null=True),
        ),
    ]
